### ISSUE TITLE
Highlighted Text not visible in Zellij

### ISSUE THREAD

**Issue by jkjarvis** [basecamp/omakub#105] opened 2024-06-12 14:47 UTC
When working with Zellij and using highlight for copying or other purposes, the highlighted section isn't visible. I think since we are "darking" the highlighted portion with same theme color but a darker gradient, it isn't visible. Maybe need to use compliment colors if there is a config for this like white over grey etc.

**Comment by giyany** [comment] 2024-06-17 08:33
Copy+paste behavior can be different in different systems, but we've seen with Zellij + Alacritty the copy+paste is straightforward and reliable, usually *not* requiring Shift.
We've also seen some themes in which the default highlight is too dark for the user to see. Omakub seems to come with several themes, so I'd start with changing the theme to see if that's the case.

**Comment by manueldeprada** [comment] 2024-06-19 10:30
Yeah that works. I switched to gruvbox and selected text block is now visible in zellij

**Comment by jkjarvis** [comment] 2024-06-24 17:26
It is still very dark for all themes. In vim mode, it is working fine but if in shell , you do cat <some_file> then highlight the output, it is not visible.

**Comment by ad798** [comment] 2024-06-25 17:43
> "Eduard You have to hold shift down to select for the system clipboard" ?

In my case, I can confirm that the highlight is too dark but is possible to copy the content from the terminal. Besides, holding shift down highlights the line with a visible color, as seen below:

![image](https://github.com/basecamp/omakub/assets/72769916/01efab86-fbd4-41ba-a263-869ef0c0b733)

**Comment by ad798** [comment] 2024-07-04 19:02
The new Omakub Manual states in the [clipobard section:](https://manual.omakub.org/1/read/34/clipboard)

> Zellij requires that you hold down Shift when you select a line in the terminal that you wish to copy to the system clipboard.

So, I think is fine to close this issue.

**Comment by florentdestremau** [comment] 2024-07-04 20:22
there are still issues on my side to select multines, because the borders of zellij are included

**Comment by giyany** [comment] 2024-07-05 13:31
@florentdestremau 
This is a separate issue. In any case, borders can be disabled with ctrl+p z.

**Comment by florentdestremau** [comment] 2024-07-05 14:17
thanks for the tip ! This should be a real issue in zellij.

**Closed** 2024-07-27 14:59 UTC

**Comment by nickpoorman** [comment] 2024-08-18 01:22
If you want a good contrasting color for the Zellij bg (subtract the `fg` RGB values from 255... ie `fg 169 177 214`) try:
Red: 
255−169=86
Green: 
255−177=78
Blue: 
255−214=41

So: `bg 86 78 41`
