### ISSUE TITLE
Menu Bar Items Disappear

### ISSUE THREAD

**Issue by GimpyHand** [basecamp/omakub#209] opened 2024-07-12 20:00 UTC
The top menu bar items for Ubuntu itself disappear and requires a system reboot in order to display again. Not sure which extension is causing the issue but toggling the "blur" extension sometimes resets the bar, but not always.

**Comment by thomas992** [comment] 2024-07-12 22:32
Are you using the stock NVIDIA drivers? I had a similar issue when I was running the 535 drivers. The current NVIDIA drivers have an issue with 24.04, download the new feature branch released in July this year if you are using NVIDIA. I think that the documentation should mention this the 535 driver is over a year old.

**Comment by MislavPukljak** [comment] 2024-07-13 10:02
Probably the problem is with Pano extension. There ware few issues about this problem already.
At least I assume it's the same problem.
#180 #205

**Comment by dhh** [comment] 2024-07-14 08:47
Please do report this on the pano repository. I haven't seen any issues, but they haven't made a final release. So I'm sure they'd be happy to get crash reports!

**Closed** 2024-07-27 15:01 UTC
