### ISSUE TITLE
Bash Script Not French-friendly

### ISSUE THREAD

**Issue by Kobytes** [basecamp/omakub#168] opened 2024-06-25 20:28 UTC
There's an issue with the Bash script. Currently, the script doesn't work properly on Ubuntu systems configured in French. This is because the script specifically looks for folder names in English, such as "Downloads", "Documents", etc (as far as I can see).

However, on a French version of Ubuntu, these directories have different names, such as "Téléchargements", "Documents", etc. This prevents the script from running properly as it cannot find the expected directories.

I know that most developers (even French ones) have their OS in English, so I think it would be interesting to make it a little more "international" -- at least for those who have their OS in French and like the Omakub principle.

**Comment by rmacklin** [comment] 2024-06-25 20:32
This is a duplicate of https://github.com/basecamp/omakub/issues/91 - the issue is already fixed on `master` in https://github.com/basecamp/omakub/commit/ec7655e75e6a8806c49b16c624c56ea75ff1eb51 but has not yet landed in the `stable` branch.

**Closed** 2024-07-03 17:23 UTC
